###testing apis
post http://localhost:8000/api/v1/register
Content-Type: application/json

{
    "fName":"marjina",
    "lName":"vvx",
    "email":"apple@apple.com",
    "password":"123456"
}

###testing apis
post http://localhost:8000/api/v1/login
Content-Type: application/json

{
    "email":"apple@apple.com",
    "password":"praveen1"
}


###working on logout endpoint
post http://localhost:8000/api/v1/logout

###password change
post http://localhost:8000/api/v1/change-password
Content-Type: application/json

{
    "email":"apple@apple.com",
    "password":"123456",
    "newPassword":"praveen1"
}

###password forgot
post http://localhost:8000/api/v1/forgot-password
Content-Type: application/json

{
    "email":"apple@apple.com",
    "newPassword":"123456"
}

###product api check
post http://localhost:8000/api/v1/product
Content-Type: application/json

{
    "name":"Mobile",
    "category":"Elec",
    "description":"very good mobile",
    "price":"$100"
}