###testing apis
post http://localhost:8000/api/v1/register
Content-Type: application/json

{
    "fName":"marjina",
    "lName":"vvx",
    "email":"apple@apple.com",
    "password":"123456"
}

###testing apis
post http://localhost:8000/api/v1/login
Content-Type: application/json

{
    "email":"apple@apple.com",
    "password":"123456"
}


###working on logout endpoint
get http://localhost:8000/api/v1/logout
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFAYS5jb20iLCJpYXQiOjE3MDU1MDEwMzEsImV4cCI6MTcwNTUwNDYzMX0.Pa9FfO_Sbe67VRNDU8Nk88IQ-w6IIaUVBF3c0_SRXT

###password change
post http://localhost:8000/api/v1/change-password
Content-Type: application/json

{
    "email":"apple@apple.com",
    "password":"123456",
    "newPassword":"praveen1"
}

###password forgot
post http://localhost:8000/api/v1/forgot-password
Content-Type: application/json

{
    "email":"apple@apple.com",
    "newPassword":"123456"
}